[debug] [2025-03-18T14:27:51.794Z] ----------------------------------------------------------------------
[debug] [2025-03-18T14:27:51.795Z] Command:       /usr/local/bin/node /usr/local/bin/firebase functions:config:set gemini.api_key=AIzaSyB5AaDRa9WsyoomPQviV7JSoqGlNbHaTLs
[debug] [2025-03-18T14:27:51.796Z] CLI Version:   13.34.0
[debug] [2025-03-18T14:27:51.796Z] Platform:      darwin
[debug] [2025-03-18T14:27:51.796Z] Node Version:  v20.11.1
[debug] [2025-03-18T14:27:51.796Z] Time:          Tue Mar 18 2025 19:57:51 GMT+0530 (India Standard Time)
[debug] [2025-03-18T14:27:51.796Z] ----------------------------------------------------------------------
[debug] 
[debug] [2025-03-18T14:27:51.797Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2025-03-18T14:27:56.829Z] Error: Timed out.
    at Timeout._onTimeout (/usr/local/lib/node_modules/firebase-tools/lib/utils.js:269:49)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
[error] 
[error] Error: An unexpected error has occurred.
[debug] [2025-03-18T14:28:19.440Z] ----------------------------------------------------------------------
[debug] [2025-03-18T14:28:19.446Z] Command:       /usr/local/bin/node /usr/local/bin/firebase functions:config:set gemini.api_key=AIzaSyB5AaDRa9WsyoomPQviV7JSoqGlNbHaTLs
[debug] [2025-03-18T14:28:19.447Z] CLI Version:   13.34.0
[debug] [2025-03-18T14:28:19.447Z] Platform:      darwin
[debug] [2025-03-18T14:28:19.447Z] Node Version:  v20.11.1
[debug] [2025-03-18T14:28:19.447Z] Time:          Tue Mar 18 2025 19:58:19 GMT+0530 (India Standard Time)
[debug] [2025-03-18T14:28:19.447Z] ----------------------------------------------------------------------
[debug] 
[debug] [2025-03-18T14:28:19.448Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2025-03-18T14:28:24.481Z] Error: Timed out.
    at Timeout._onTimeout (/usr/local/lib/node_modules/firebase-tools/lib/utils.js:269:49)
    at listOnTimeout (node:internal/timers:573:17)
    at process.processTimers (node:internal/timers:514:7)
[error] 
[error] Error: An unexpected error has occurred.
